# Importing NumPy Library:

In [1]:
import numpy as np

# Taking List as an input for an array creation:

In [2]:
np.array([20,30,40,89,53])

array([20, 30, 40, 89, 53])

In [3]:
arr = np.array([20,30,40,89,53])
print(arr)

[20 30 40 89 53]


In [4]:
ar = arr[1:4]
ar

array([30, 40, 89])

In [5]:
ar[2] = 50
ar

array([30, 40, 50])

In [6]:
arr

array([20, 30, 40, 50, 53])

In [7]:
ar = np.array([20,45,87,69,34])
ar1 = ar[1:5].copy()
print(ar1)

[45 87 69 34]


In [8]:
ar1[2] = 98
print(ar1)

[45 87 98 34]


In [9]:
print(ar)

[20 45 87 69 34]


In [5]:
l = [[34,89,76,82],[12,93,45,76]]
arr = np.array(l)
print(arr)

[[34 89 76 82]
 [12 93 45 76]]


In [6]:
l = [[34,89,76,82],[12,93,45]]
arr = np.array(l)
print(arr)

[list([34, 89, 76, 82]) list([12, 93, 45])]


C:\Users\mouni\AppData\Local\Temp\ipykernel_29972\1965909106.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array(l)


In [7]:
l = [[34,89,76,82],[12,93,np.nan,76]]
arr = np.array(l)
print(arr)

[[34. 89. 76. 82.]
 [12. 93. nan 76.]]


In [8]:
l = [[34,89,76,82],[12,93,True,76]]
arr = np.array(l)
print(arr)

[[34 89 76 82]
 [12 93  1 76]]


In [9]:
l = [[34,89,76,82],[12,93,False,76]]
arr = np.array(l)
print(arr)

[[34 89 76 82]
 [12 93  0 76]]


In [10]:
l = [[34,'hii',76,82],[12,93,False,76]]
arr = np.array(l)
print(arr)

[['34' 'hii' '76' '82']
 ['12' '93' 'False' '76']]


In [11]:
l = [[34,'hii',76,82],['hello',93,True,76]]
arr = np.array(l)
print(arr)

[['34' 'hii' '76' '82']
 ['hello' '93' 'True' '76']]


In [12]:
bool(0)

False

In [14]:
bool(1)

True

In [15]:
bool(0.001)

True

# Taking Tuple as input for an array creation:

In [18]:
import numpy as np
t = (45,67,83,54,24,12,'a','b','c')
arr1 = np.array(t)
arr1

array(['45', '67', '83', '54', '24', '12', 'a', 'b', 'c'], dtype='<U11')

In [10]:
t = (45,67,83,54,24,12,98,84,23)

In [11]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [12]:
a = np.arange(11,21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
a = np.arange(11,21,2)
a

array([11, 13, 15, 17, 19])

In [14]:
a = np.arange(60,15, -3)
a

array([60, 57, 54, 51, 48, 45, 42, 39, 36, 33, 30, 27, 24, 21, 18])

In [16]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
a.reshape(2,4)

ValueError: cannot reshape array of size 9 into shape (2,4)

In [19]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [20]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
b = np.zeros((4,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
c = np.ones((4,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
c*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [28]:
mat = np.arange(0,27)
mat1 = np.reshape(mat, (9,3), 'F')
print(mat1)

[[ 0  9 18]
 [ 1 10 19]
 [ 2 11 20]
 [ 3 12 21]
 [ 4 13 22]
 [ 5 14 23]
 [ 6 15 24]
 [ 7 16 25]
 [ 8 17 26]]


In [29]:
mat = np.arange(0,27)
mat1 = np.reshape(mat, (3,9), 'F')
print(mat1)

[[ 0  3  6  9 12 15 18 21 24]
 [ 1  4  7 10 13 16 19 22 25]
 [ 2  5  8 11 14 17 20 23 26]]


In [30]:
mat = np.arange(0,27)
mat1 = np.reshape(mat, (9,3), 'C')
print(mat1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]]


In [32]:
# bydefault 'C'
mat = np.arange(0,27)
mat1 = np.reshape(mat, (3,9), 'C')
print(mat1)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


In [33]:
mat1.T

array([[ 0,  9, 18],
       [ 1, 10, 19],
       [ 2, 11, 20],
       [ 3, 12, 21],
       [ 4, 13, 22],
       [ 5, 14, 23],
       [ 6, 15, 24],
       [ 7, 16, 25],
       [ 8, 17, 26]])

In [46]:
a = np.arange(9)
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
a = np.arange(6,15)
c = a.reshape(3,3)
c

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [48]:
b+c

array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [49]:
b-c

array([[-6, -6, -6],
       [-6, -6, -6],
       [-6, -6, -6]])

In [50]:
mat1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [51]:
print(mat1.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [53]:
vector = np.linspace(0,20,3)
print(vector)

[ 0. 10. 20.]


In [55]:
vector = np.linspace(0,26,10)
print(vector)

[ 0.          2.88888889  5.77777778  8.66666667 11.55555556 14.44444444
 17.33333333 20.22222222 23.11111111 26.        ]


In [57]:
vector = np.linspace(10,30,12)
print(vector)

[10.         11.81818182 13.63636364 15.45454545 17.27272727 19.09090909
 20.90909091 22.72727273 24.54545455 26.36363636 28.18181818 30.        ]


In [59]:
EU_Sales = [456, 897,643,234]
APAC_Sales = [789,435,267,983]
US_Sales = [346,879,652,389]
sales = np.array([EU_Sales, APAC_Sales, US_Sales])
print(sales)

[[456 897 643 234]
 [789 435 267 983]
 [346 879 652 389]]


In [61]:
sales[2]

array([346, 879, 652, 389])

In [62]:
sales[1][1]

435

In [63]:
sales[2][1]

879

In [64]:
r = {'EU':0, 'APAC':1, 'US':2}
q = {'Q1':0, 'Q2':1,'Q3':2, 'Q4':3}
sales[r['US']][q['Q3']]

652

In [65]:
sales[r['APAC']][q['Q3']]

267

In [69]:
def convertto (deg):
    F = (deg*915)+32
    return(F)
temp = 38
temp = convertto (temp)
print(temp)

34802


In [67]:
temp = 38
temp = convertto (temp)
print(temp)

34802


In [68]:
convertto(38)

34802

In [71]:
l = [50,80,90,70,54,38,32]
l1 = []
for i in l:
    if(i != 20):
        l1.append(i)
print(l1)

[50, 80, 90, 70, 54, 38, 32]


In [72]:
l = [50,80,90,70,54,38,32,70]
l1 = []
for i in l:
    if(i != 70):
        l1.append(i)
print(l1)

[50, 80, 90, 54, 38, 32]


In [73]:
l

[50, 80, 90, 70, 54, 38, 32, 70]

In [81]:
for i in l:
    if(i == 54):
        l.remove(i)
print(l)

[50, 80, 90, 70, 38, 32, 70]


In [82]:
def histogram(items):
    for n in items:
        output = ''
        times = n
        while(times > 0):
            output+='@'
            times = times - 1
            print(times)
        print(output)

In [83]:
histogram([2,3,6,5])

1
0
@@
2
1
0
@@@
5
4
3
2
1
0
@@@@@@
4
3
2
1
0
@@@@@


In [87]:
def histogram(items):
    for n in items:
        output = ''
        times = n
        while(times > 0):
            output+='@'
            times = times - 1
        print(output)

In [88]:
histogram([2,3,6,5])

@@
@@@
@@@@@@
@@@@@


In [89]:
def histogram(items):
    for n in items:
        output = ''
        times = n
        while(times > 0):
            output+='@'
            print(times)
            times = times - 1
        print(output)

In [90]:
histogram([2,3,6,5])

2
1
@@
3
2
1
@@@
6
5
4
3
2
1
@@@@@@
5
4
3
2
1
@@@@@


In [91]:
def test_number5(x,y):
    if x == y or abs(x-y) == 5 or (x+y) == 5:
        return True
    else:
        return False
print(test_number5(7,2))

True


In [92]:
print(test_number5(10,10))

True


In [95]:
def max_num_in_list (list):
    max = list[0]
    print(list[0])
    for a in list:
        if a > max:
            max = a
    return max
print(max_num_in_list([1,2,-8,0]))

1
2


In [100]:
def long_words(n, str):
    word_len = []
    txt = str.split(" ")
    for x in txt:
        if len(x)>n:
            word_len.append(x)
    return word_len
print(long_words(3, "The quick brown for jumps over the lazy dog"))

['quick', 'brown', 'jumps', 'over', 'lazy']


In [101]:
x = ("The quick brown for jumps over the lazy dog")
x.split(" ")

['The', 'quick', 'brown', 'for', 'jumps', 'over', 'the', 'lazy', 'dog']

In [102]:
color = ['red', 'green', 'white', 'black', 'pink', 'yellow']
color

['red', 'green', 'white', 'black', 'pink', 'yellow']

In [103]:
color =[x for(i,x) in enumerate(color) if i not in(0,4,5)]
print(color)

['green', 'white', 'black']


# Slicing of an Array:

In [104]:
import numpy as np

In [105]:
ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
print(ar[2:], '\n')

[2 3 4 5 6 7 8 9] 



In [107]:
print(ar[:5])

[0 1 2 3 4]


In [108]:
print(ar[2:7])

[2 3 4 5 6]


In [109]:
print(ar[0:10:2])

[0 2 4 6 8]


In [110]:
print(ar[1:7:2])

[1 3 5]


In [111]:
print(ar[::2])

[0 2 4 6 8]


In [112]:
print(ar[::-2])

[9 7 5 3 1]


In [113]:
ar_slice = slice(1, 10, 2)
print(ar_slice)
print(ar[ar_slice])

slice(1, 10, 2)
[1 3 5 7 9]


In [114]:
ar1 = np.arange(9)
print(ar1)
ar1 = ar1.reshape(3,3)
ar1

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
ar1[1]

array([3, 4, 5])

In [116]:
ar1[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [117]:
ar1[1:,1:]

array([[4, 5],
       [7, 8]])

In [118]:
ar1[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [119]:
ar1[1:, :2]

array([[3, 4],
       [6, 7]])

In [120]:
print(ar1.shape)

(3, 3)


In [121]:
print(ar1.ndim)

2


In [122]:
print(ar1.itemsize)

4


In [123]:
print(ar1.dtype)

int32


In [124]:
print(ar1.size)

9


In [125]:
print(ar1.min())

0


In [126]:
print(ar1.max())

8


In [127]:
print(np.sqrt(ar1))

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [128]:
print(ar1.sum())

36


In [129]:
print(np.std(ar1))

2.581988897471611


In [130]:
ar2 = np.empty([3,2],dtype = float)
print(ar2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [131]:
ar2 = np.empty([3,2], dtype = bool)
print(ar2)

[[False False]
 [False False]
 [False False]]


In [134]:
ar2 = np.empty([3,2], dtype = int)
print(ar2)

[[         0          0]
 [         0 1076101120]
 [         0 1077149696]]


In [136]:
ar2 = np.empty([3,2], dtype = str)
print(ar2)

[['' '']
 ['' '']
 ['' '']]


In [137]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [138]:
import numpy as np

In [139]:
for name in dir(np):
    print(name, end = '\t')

ALLOW_THREADS	AxisError	BUFSIZE	Bytes0	CLIP	ComplexWarning	DataSource	Datetime64	ERR_CALL	ERR_DEFAULT	ERR_IGNORE	ERR_LOG	ERR_PRINT	ERR_RAISE	ERR_WARN	FLOATING_POINT_SUPPORT	FPE_DIVIDEBYZERO	FPE_INVALID	FPE_OVERFLOW	FPE_UNDERFLOW	False_	Inf	Infinity	MAXDIMS	MAY_SHARE_BOUNDS	MAY_SHARE_EXACT	MachAr	ModuleDeprecationWarning	NAN	NINF	NZERO	NaN	PINF	PZERO	RAISE	RankWarning	SHIFT_DIVIDEBYZERO	SHIFT_INVALID	SHIFT_OVERFLOW	SHIFT_UNDERFLOW	ScalarType	Str0	Tester	TooHardError	True_	UFUNC_BUFSIZE_DEFAULT	UFUNC_PYVALS_NAME	Uint64	VisibleDeprecationWarning	WRAP	_NoValue	_UFUNC_API	__NUMPY_SETUP__	__all__	__builtins__	__cached__	__config__	__deprecated_attrs__	__dir__	__doc__	__expired_functions__	__file__	__getattr__	__git_version__	__loader__	__mkl_version__	__name__	__package__	__path__	__spec__	__version__	_add_newdoc_ufunc	_distributor_init	_financial_names	_globals	_mat	_pytesttester	_version	abs	absolute	add	add_docstring	add_newdoc	add_newdoc_ufunc	alen	all	allclose	alltrue	amax	amin	angle	an

In [140]:
ar1 = np.array([1,2,3], dtype = np.float64)
ar1

array([1., 2., 3.])

In [142]:
ar1 = np.array([1, 2.6, 3.4], dtype = np.int)
ar1

C:\Users\mouni\AppData\Local\Temp\ipykernel_20372\3702547900.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ar1 = np.array([1, 2.6, 3.4], dtype = np.int)


array([1, 2, 3])

In [143]:
ar1 = np.array([1, 600, 3.4], dtype = np.int8)
ar1

array([ 1, 88,  3], dtype=int8)

In [144]:
ar1 = np.array([1, 600, 4751], dtype = np.int8)
ar1

array([   1,   88, -113], dtype=int8)

In [145]:
ar1 = np.array([1, 600, 4751], dtype = np.int32)
ar1

array([   1,  600, 4751])

In [148]:
ar1 = np.array([1, 2.5, 3.4], dtype = np.int8)
ar1

array([1, 2, 3], dtype=int8)

In [149]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [150]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [151]:
arr = np.array([[3,2,4], [5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [152]:
print(arr)

[[3 2 4]
 [5 0 1]]


In [153]:
print(np.sort(arr, axis = 0))

[[3 0 1]
 [5 2 4]]


In [154]:
print(np.sort(arr, axis = 1))

[[2 3 4]
 [0 1 5]]


In [155]:
arr = np.array([[3,2,4],[5,0,1]])
arr

array([[3, 2, 4],
       [5, 0, 1]])

In [156]:
-arr

array([[-3, -2, -4],
       [-5,  0, -1]])

In [157]:
arr = np.sort(-arr)
print(arr)

[[-4 -3 -2]
 [-5 -1  0]]


In [158]:
a = -np.sort(-arr)
print(arr)

[[-4 -3 -2]
 [-5 -1  0]]


In [159]:
arr = np.array([[3,2,4],[5,0,1]])
arr

array([[3, 2, 4],
       [5, 0, 1]])

In [160]:
arr = -np.sort(-arr)
print(arr)

[[4 3 2]
 [5 1 0]]


In [162]:
arr = np.arange(10,19)
arr = np.delete(arr, [2,5])
print(arr)

[10 11 13 14 16 17 18]


In [163]:
arr = np.arange(10,19)
print(arr)

[10 11 12 13 14 15 16 17 18]


In [164]:
arr = np.delete(arr, [2,5])
print(arr)

[10 11 13 14 16 17 18]


In [166]:
arr = np.arange(10,22)
arr1 = arr.reshape(3,4)
arr1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [167]:
a = np.delete(arr1, 1, 0)
a

array([[10, 11, 12, 13],
       [18, 19, 20, 21]])

In [168]:
a = np.delete(arr1, 1, 1)
a

array([[10, 12, 13],
       [14, 16, 17],
       [18, 20, 21]])

In [170]:
a = np.delete(arr1, 1, 0)
a

array([[10, 11, 12, 13],
       [18, 19, 20, 21]])

In [171]:
m = np.arange(30)
n = m.reshape(2, 5, 3)
n

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [172]:
a = np.delete(n, 1, 0)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

In [173]:
a = np.delete(n, 1, 1)
a

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [174]:
a = np.delete(n, 1, 2)
a

array([[[ 0,  2],
        [ 3,  5],
        [ 6,  8],
        [ 9, 11],
        [12, 14]],

       [[15, 17],
        [18, 20],
        [21, 23],
        [24, 26],
        [27, 29]]])